### ISSUE TITLE
ValueError in Tracing the coronal field lines

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#79] opened 2022-10-13 20:38 UTC
I am using the coronal model and I am trying to trace the field lines in 3D as follows: 

```python
directory = '/path/to/folder/'
mas_output = MASOutput(directory)

tracer = FortranTracer()
plotter = MASPlotter(mas_output)

nseeds = 10
r = np.ones(nseeds**2)*30*u.R_sun # should show the traced field lines up to 30 Rsun, right? 
lat = np.linspace(-89, 89, nseeds**2, endpoint=False)*u.deg
lon = np.random.rand(nseeds**2)*360*u.deg

# Do the tracing 
br = mas_output['br']
flines = tracer.trace(mas_output, r=r, lat=lat, lon=lon)

for fline in flines:
    # Set color with polarity near the inner boundary 
    color = (br.sample_at_coords(np.mod(fline.lon[0], 2*np.pi*u.rad), 
                                 fline.lat[0], 
                                 fline.r[0]*u.R_sun) > 0)
    
    color = {1: 'red', 0: 'blue'}[int(color)]
    plotter.add_fline(fline, color=color)

# Add a sphere at the inner boundary of the model 
plotter.add_sphere(np.min(br.r_coords))
plotter.show(cpos='xy', jupyter_backend='panel')
```

Knowing that: 
`br.r_coords --> [0.99956024, 1.0004398, 1.0013049, …, 28.465059, 29.488354, 30.511646] R⊙` 

I get this error: 
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [241], in <cell line: 16>()
     14 flines = tracer.trace(mas_output, r=r, lat=lat, lon=lon)
     16 for fline in flines:
     17     # Set color with polarity near the inner boundary 
---> 18     color = (br.sample_at_coords(np.mod(fline.lon[0], 2*np.pi*u.rad), 
     19                                  fline.lat[0], 
     20                                  fline.r[0]*u.R_sun) > 0)
     22     color = {1: 'red', 0: 'blue'}[int(color)]
     23     plotter.add_fline(fline, color=color)

File ~/.conda/envs/psp/lib/python3.9/site-packages/astropy/units/decorators.py:302, in QuantityInput.__call__.<locals>.wrapper(*func_args, **func_kwargs)
    300 # Call the original function with any equivalencies in force.
    301 with add_enabled_equivalencies(self.equivalencies):
--> 302     return_ = wrapped_function(*func_args, **func_kwargs)
    304 # Return
    305 ra = wrapped_signature.return_annotation

File ~/.conda/envs/psp/lib/python3.9/site-packages/psipy/model/variable.py:453, in Variable.sample_at_coords(self, lon, lat, r, t)
    448     if not (bounds[0] <= coord_bounds[0] and coord_bounds[1] <= bounds[1]):
    449         warnings.warn(
    450             f"At least one sample coordinate is outside bounds {bounds} in {dim} dimension. Sample coordinate min/max values are {coord_bounds}."
    451         )
--> 453 values_x = interpolate.interpn(
    454     points, values, xi, bounds_error=False, fill_value=np.nan
    455 )
    456 return values_x * self._unit

File ~/.conda/envs/psp/lib/python3.9/site-packages/scipy/interpolate/interpolate.py:2677, in interpn(points, values, xi, method, bounds_error, fill_value)
   2675 for i, p in enumerate(points):
   2676     if not np.all(np.diff(p) > 0.):
-> 2677         raise ValueError("The points in dimension %d must be strictly "
   2678                          "ascending" % i)
   2679     if not np.asarray(p).ndim == 1:
   2680         raise ValueError("The points in dimension %d must be "
   2681                          "1-dimensional" % i)

ValueError: The points in dimension 0 must be strictly ascending
``` 

Can you please explain how to fix it?

**Comment by thepeteriley** [comment] 2022-10-13 21:03
Hi Mohamed, Can you point me to the files you're trying to visualise (PSI or CCMC's website?) and I'll try to reproduce the error?

**Comment by MohamedNedal** [comment] 2022-10-13 22:38
Hi Pete @thepeteriley , I downloaded the files from the PSI [link](https://www.predsci.com/mhdweb/data_access.php?ps-data-id=high%2Fhmi_mast_mas_std_0201&ps-date-cr=date&ps-month=04&ps-day=03&ps-year=2019&ps-hour=12&ps-minute=10&ps-cr-num=2261&ps-cr-lon=1.00&solution=corona&submit=Update+Data)

**Comment by MohamedNedal** [comment] 2022-10-14 17:11
It seems that all the field lines have some issues. I've checked with these few lines: 

```
for idx in np.arange(len(flines)):
    try:
        (br.sample_at_coords(np.mod(fline.lon[idx], 2*np.pi*u.rad), fline.lat[idx], fline.r[idx]*u.R_sun) > 0)
    except:
        print('Problem at fline ' + str(idx))
``` 

Here's the output: 
```
Problem at fline 0
Problem at fline 1
Problem at fline 2
Problem at fline 3
Problem at fline 4
Problem at fline 5
Problem at fline 6
Problem at fline 7
Problem at fline 8
Problem at fline 9
Problem at fline 10
Problem at fline 11
Problem at fline 12
Problem at fline 13
Problem at fline 14
Problem at fline 15
Problem at fline 16
Problem at fline 17
Problem at fline 18
Problem at fline 19
Problem at fline 20
Problem at fline 21
Problem at fline 22
Problem at fline 23
Problem at fline 24
Problem at fline 25
Problem at fline 26
Problem at fline 27
Problem at fline 28
Problem at fline 29
Problem at fline 30
Problem at fline 31
Problem at fline 32
Problem at fline 33
Problem at fline 34
Problem at fline 35
Problem at fline 36
Problem at fline 37
Problem at fline 38
Problem at fline 39
Problem at fline 40
Problem at fline 41
Problem at fline 42
Problem at fline 43
Problem at fline 44
Problem at fline 45
Problem at fline 46
Problem at fline 47
Problem at fline 48
Problem at fline 49
Problem at fline 50
Problem at fline 51
Problem at fline 52
Problem at fline 53
Problem at fline 54
Problem at fline 55
Problem at fline 56
Problem at fline 57
Problem at fline 58
Problem at fline 59
Problem at fline 60
Problem at fline 61
Problem at fline 62
Problem at fline 63
Problem at fline 64
Problem at fline 65
Problem at fline 66
Problem at fline 67
Problem at fline 68
Problem at fline 69
Problem at fline 70
Problem at fline 71
Problem at fline 72
Problem at fline 73
Problem at fline 74
Problem at fline 75
Problem at fline 76
Problem at fline 77
Problem at fline 78
Problem at fline 79
Problem at fline 80
Problem at fline 81
Problem at fline 82
Problem at fline 83
Problem at fline 84
Problem at fline 85
Problem at fline 86
Problem at fline 87
Problem at fline 88
Problem at fline 89
Problem at fline 90
Problem at fline 91
Problem at fline 92
Problem at fline 93
Problem at fline 94
Problem at fline 95
Problem at fline 96
Problem at fline 97
Problem at fline 98
Problem at fline 99
Problem at fline 100
Problem at fline 101
Problem at fline 102
Problem at fline 103
Problem at fline 104
Problem at fline 105
Problem at fline 106
Problem at fline 107
Problem at fline 108
Problem at fline 109
Problem at fline 110
Problem at fline 111
Problem at fline 112
Problem at fline 113
Problem at fline 114
Problem at fline 115
Problem at fline 116
Problem at fline 117
Problem at fline 118
Problem at fline 119
Problem at fline 120
Problem at fline 121
Problem at fline 122
Problem at fline 123
Problem at fline 124
Problem at fline 125
Problem at fline 126
Problem at fline 127
Problem at fline 128
Problem at fline 129
Problem at fline 130
Problem at fline 131
Problem at fline 132
Problem at fline 133
Problem at fline 134
Problem at fline 135
Problem at fline 136
Problem at fline 137
Problem at fline 138
Problem at fline 139
Problem at fline 140
Problem at fline 141
Problem at fline 142
Problem at fline 143
```

**Comment by AthKouloumvakos** [comment] 2022-10-14 22:48
I get the same error with another cube, specifically: `cr2250-high/hmi_mast_mas_std_0101/`
but it seems to me that it is not a cube dependent issue.

It seems that sample_at_coords fail because the passing array in interpn is not accending.

So, when I do (note I had to remove br_r0.hdf first from path):

```python
model = MASOutput('./PsiPy/cr2250-high/hmi_mast_mas_std_0101/corona')
model["rho"].sample_at_coords(0 * np.pi * u.rad, 0 * np.pi * u.rad, 1 * u.R_sun)
```
I get the same error.
 
Exploring this further I find that just before the https://github.com/predsci/PsiPy/blob/e68fd6d04e597744fd3901adae85c2e899496fee/psipy/model/variable.py#L453

the `points` variable which is the cube's phi, th, r vectors are not accending and that makes interpn to error.

For example the 
```python
print(points[0][0:5])
print(points[1][0:5])
print(points[2][0:5])
```
just before the intern gives:
```python
[ 0.01054209 -0.01054226  0.01054226  0.03162677  0.05271129]
[-1.58962719 -1.5519654  -1.51446025 -1.47737829 -1.4408807 ]
[0.99970806 1.00029194 1.00087321 1.00144744 1.00201201]
```
it seems that the extension in phi is causing the problem because the array is not ascending. 

This problem should be captured by these line

https://github.com/predsci/PsiPy/blob/e68fd6d04e597744fd3901adae85c2e899496fee/psipy/model/variable.py#L416

but the index is wrong there. It should be `if not np.all(np.diff(points[0]) >= 0): ` I guess.

I think that these lines need a correction at the index:
https://github.com/predsci/PsiPy/blob/e68fd6d04e597744fd3901adae85c2e899496fee/psipy/model/variable.py#L418
https://github.com/predsci/PsiPy/blob/e68fd6d04e597744fd3901adae85c2e899496fee/psipy/model/variable.py#L420

I didn't have time to trase the source of the error in the phi extension but I think it is somewhere between lines 423-431 in sample_at_coords.

**Comment by dstansby** [comment] 2022-10-23 15:27
Thanks for the clear bug report and investigation all - this should be fixed in #83. The issue was that some MAS outputs already have the extra ghost cell at phi=2pi.

**Comment by AthKouloumvakos** [comment] 2022-10-24 03:14
@dstansby It seems that after https://github.com/predsci/PsiPy/pull/83 the situation got better but there is a slight problem again.

So when:

```
from psipy.model import MASOutput
import numpy as np
from astropy import units as u

model = MASOutput('./PsiPy/cr2250-high/hmi_mast_mas_std_0101/corona')
b = model["br"].sample_at_coords(0 * np.pi * u.rad, 0 * np.pi * u.rad, 1 * u.R_sun)
print(b)
n = model["rho"].sample_at_coords(0 * np.pi * u.rad, 0 * np.pi * u.rad, 1 * u.R_sun)
print(n)
```

The interpolation works fine with **br** but with **rho** it fails with the  

`RuntimeError("Longitude coordinates are not monotonically increasing").`

What happens I think is that this check:

`if not np.allclose(pcoords[0], pcoords[-1] - (2 * np.pi), rtol=0, atol=1e-6):`

propably does not work as expected.

For `br` the `print(pcoords[0], pcoords[-1], pcoords[-1]-(2 * np.pi))` before the check gives:

`0.0 6.2831854820251465 1.7484556025237907e-07`

while for `rho` the `print(pcoords[0], pcoords[-1], pcoords[-1]-(2 * np.pi))` it gives:

`-0.010542257688939571 6.293727397918701 0.01054209073911494`

So, for `br` the cube never extends and for 'rho' it extends incorrectly.

The parameters are given in a staggered grid so some parameters defined at the cell centers and others defined at the cell faces, for example

```
for p in ['bp', 'br', 'bt', 'rho', 'va', 'vp', 'vr', 'vt']:
    print(model[p].data.coords["phi"].values[[0,1,-2,-1]])
```
and this makes the extension a bit more complex.

What do you think?

**Comment by AthKouloumvakos** [comment] 2022-10-24 18:31
Exploring this further I find that:

A correct extension for `br` would be for example:
```
pcoords = np.append(pcoords, pcoords[1] + 2 * np.pi)
pcoords = np.insert(pcoords, 0,  pcoords[-3] - 2 * np.pi )
```

while for `rho`
```
pcoords = np.append(pcoords, pcoords[2] + 2 * np.pi)
pcoords = np.insert(pcoords, 0,  pcoords[-4] - 2 * np.pi )
```

So I think that in the end the extension would be like:
```
pcoords = points[0]
if pcoords[0]==0:
    j = [1, -3]
elif pcoords[0]<0:
    j = [2, -4]
pcoords = np.append(pcoords, pcoords[j[0]] + 2 * np.pi)
pcoords = np.insert(pcoords, 0,  pcoords[j[1]] - 2 * np.pi)
points[0] = pcoords
```

However, I am a bit sceptical if an extension is realy needed in any case. 

The range of longitude of the grid for any of the paremeters aways contain 0 and 2pi, right? 
So since the input longitude is always in [0,2*pi] I cannot see the benefit of this extension here exept from enabling a cubic extrapolation that would be more accurate in the edges or if we want to extrapolate the `br` values to `rho` grid for example. So, I think the sample_at_coords sould not extend the data by default.

**Comment by dstansby** [comment] 2022-11-04 22:36
Thanks again for detailed investigation.

> However, I am a bit sceptical if an extension is realy needed in any case.

The extension is needed if there's not a full wrap-around of the phi coordinates, e.g. if the first point in the phi coords is just above zero and the last point just below 2pi, the extension neeeds to happen to allow a point at 0/2pi to be interpolated.

The case posted in the comment above is fixed in https://github.com/predsci/PsiPy/pull/96, so I'll close this. If you find any more issues (thanks a lot for testing and reporting, it's super useful!!) please do open a new issue 😃

**Closed as completed by dstansby** 2022-11-04 22:36 UTC
Labels: Bug
